Some code cleanup
bigfish-hu/payment-gateway-php-sdk pull request #2
Opened 2018-03-29 10:02 UTC by sigee

- Remove unused/unneeded imports (No need to import from the same package)
- Fix phpDoc "undefined class" issue (If you are inside a package, you need to use \ at the begen of the imported/used full qualified package. If not, the actual package will be put to the beginning of your "classname")
- Fix a phpDoc comment (A @throws was missing)
- Add missing @throws phpDoc (And some more @throws)
- Remove unneeded @throws phpDoc, because never thrown (the method never throws any Exception)
- Add default case if there is no API type defined (If the config is wrong your $clientType variable won't be set and the sprintf() method will try to use a non existing variable, so you need to handle this case also)
- Define variable before use a non-defined variable (same reason, there is no garanty your app runs into the foreach and the if and creates a $params array variable)
- Add a field declaration to avoid dynamic initialization
- Add @throws phpDoc for the unhandled Ecxeptions (there were many methods those call something that can throw exception handle it or declare it as @throws)
- Fix a typo

2018-04-10 12:31 UTC, viderspan requested changes
Thanks for your work. 

I would have two comments:

1. Please try to use the origin format so use one tab instead of four spaces.
2. Create a new pull request into the develop branch instead of master.

2018-04-12 12:07 UTC, viderspan reviewed
Please replace the 4 spaces to tab in src/BigFish/PaymentGateway.php file too. Thank you.

2018-05-04 07:39 UTC, sigee commented
@viderspan,
I've done the requested changes.
FYI:
I prefer using [PSR](https://www.php-fig.org/psr/) standards.
Eg.: [PSR-2](https://www.php-fig.org/psr/psr-2/ )
> Code MUST use 4 spaces for indenting, not tabs.

2018-05-04 11:36 UTC, viderspan approved these changes

2018-05-04 11:37 UTC, merged

2018-05-07 06:29 UTC, viderspan commented
Your code cleanup merged into master branch (2.12.2 version).
Thank you.