Add proxy support to init call
bigfish-hu/payment-gateway-php-sdk pull request #6
Opened 2022-10-14 11:06 UTC by d3n972

This PR is implementing a new Config property to allow the useage of proxies during the init api call. I hope you can accept this PR, of if further changes are needed, please propose your changes and I am more than happy to implement them.

2022-10-20 12:33 UTC, viderspan requested changes

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway/Request/Init.php
> +	public $gatewayProxy;
I think, you don't need to create this class variable, because the IP address will be checked for every API request, not just for Init.

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway/Request/Init.php
> +		$this->gatewayProxy =  PaymentGateway::getConfig()->gatewayProxy;
This is not necessary.

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway/Config.php
> + * @property string $gatewayProxy Test service URL
Please, rename the "Test service URL" to "Proxy address used for the api requests"

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway/Config.php
> +    /**
Please, use tab instead of spaces to indent.

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway/Config.php
> +	protected $gatewayProxy = '';
Please, add an empty new line after this line.

2022-10-20 12:33 UTC, viderspan commented on src/BigFish/PaymentGateway.php
> +		if ($request->gatewayProxy != '') {
Please, change the `$request->gatewayProxy` to `self::getConfig()->gatewayProxy`

It's better if this works independently of the methods (Init, Result, Close...).

2022-10-20 12:35 UTC, viderspan commented
@d3n972 

Hi Márk,

Please, modify the code based on my comments and create a new pull request into the "proxy" branch.

Thanks,
Krisztián

2022-10-22 21:27 UTC, d3n972 commented
Hi Krisztián,
Thank you for your feedback, as you requested I opened a new PR which targets the proxy branch with the modifications you requested.
- Márk.

2022-10-22 21:27 UTC, closed without merging